package mockdata

import "openclaw/mockapi/internal/models"

func Seed() models.Data {
	return models.Data{
		Tenants: []models.Tenant{
			{ID: 1, Code: "t-acme", Name: "Acme Studio", Status: "active", Plan: "pro", CreatedAt: "2026-03-01T08:00:00Z", UpdatedAt: "2026-04-01T12:00:00Z"},
			{ID: 2, Code: "t-nova", Name: "Nova Labs", Status: "active", Plan: "standard", CreatedAt: "2026-03-10T08:00:00Z", UpdatedAt: "2026-04-02T12:00:00Z"},
		},
		Clusters: []models.Cluster{
			{ID: 1, Code: "c-sh", Name: "Shanghai Cluster", Region: "cn-shanghai", Status: "healthy", NodeCount: 12, CreatedAt: "2026-02-15T00:00:00Z", UpdatedAt: "2026-04-04T10:00:00Z"},
			{ID: 2, Code: "c-bj", Name: "Beijing Cluster", Region: "cn-beijing", Status: "degraded", NodeCount: 8, CreatedAt: "2026-02-16T00:00:00Z", UpdatedAt: "2026-04-04T10:00:00Z"},
		},
		Instances: []models.Instance{
			{ID: 100, TenantID: 1, ClusterID: 1, Code: "inst-acme-prod", Name: "Acme Prod", Status: "running", Version: "1.6.3", Plan: "pro", RuntimeType: "kubernetes", Region: "cn-shanghai", Spec: map[string]string{"cpu": "2", "memory": "4Gi"}, ActivatedAt: "2026-03-05T02:00:00Z", CreatedAt: "2026-03-01T02:00:00Z", UpdatedAt: "2026-04-05T06:00:00Z"},
			{ID: 101, TenantID: 1, ClusterID: 1, Code: "inst-acme-stg", Name: "Acme Staging", Status: "backing_up", Version: "1.6.3", Plan: "standard", RuntimeType: "kubernetes", Region: "cn-shanghai", Spec: map[string]string{"cpu": "1", "memory": "2Gi"}, ActivatedAt: "2026-03-12T02:00:00Z", CreatedAt: "2026-03-10T02:00:00Z", UpdatedAt: "2026-04-05T06:00:00Z"},
			{ID: 200, TenantID: 2, ClusterID: 2, Code: "inst-nova-prod", Name: "Nova Prod", Status: "running", Version: "1.6.2", Plan: "standard", RuntimeType: "kubernetes", Region: "cn-beijing", Spec: map[string]string{"cpu": "2", "memory": "3Gi"}, ActivatedAt: "2026-03-20T02:00:00Z", CreatedAt: "2026-03-15T02:00:00Z", UpdatedAt: "2026-04-04T06:00:00Z"},
		},
		Accesses: []models.InstanceAccess{
			{InstanceID: 100, EntryType: "portal", URL: "https://acme.example.com", Domain: "acme.example.com", AccessMode: "sso", IsPrimary: true},
			{InstanceID: 100, EntryType: "admin", URL: "https://admin.acme.example.com", Domain: "admin.acme.example.com", AccessMode: "password", IsPrimary: false},
			{InstanceID: 101, EntryType: "portal", URL: "https://stg.acme.example.com", Domain: "stg.acme.example.com", AccessMode: "sso", IsPrimary: true},
			{InstanceID: 200, EntryType: "portal", URL: "https://nova.example.com", Domain: "nova.example.com", AccessMode: "sso", IsPrimary: true},
		},
		Configs: []models.InstanceConfig{
			{
				InstanceID: 100,
				Version:    7,
				Hash:       "ab12cd34",
				PublishedAt: "2026-04-03T08:00:00Z",
				UpdatedBy:  "alice",
				Settings: models.ConfigSettings{
					Model:          "gpt-5",
					AllowedOrigins: "https://acme.example.com",
					BackupPolicy:   "daily@02:00 保留 7 天",
				},
			},
			{
				InstanceID: 101,
				Version:    3,
				Hash:       "ef56gh78",
				PublishedAt: "2026-04-02T10:00:00Z",
				UpdatedBy:  "bob",
				Settings: models.ConfigSettings{
					Model:          "gpt-5-mini",
					AllowedOrigins: "https://stg.acme.example.com",
					BackupPolicy:   "manual only",
				},
			},
			{
				InstanceID: 200,
				Version:    5,
				Hash:       "yz90zz11",
				PublishedAt: "2026-04-01T06:00:00Z",
				UpdatedBy:  "carol",
				Settings: models.ConfigSettings{
					Model:          "gpt-4.1",
					AllowedOrigins: "https://nova.example.com",
					BackupPolicy:   "daily@03:00 保留 14 天",
				},
			},
		},
		Backups: []models.BackupRecord{
			{ID: 1, InstanceID: 100, BackupNo: "bk-20260403-001", Type: "scheduled", Status: "succeeded", SizeBytes: 512 * 1024 * 1024, StartedAt: "2026-04-03T01:00:00Z", FinishedAt: "2026-04-03T01:05:00Z"},
			{ID: 2, InstanceID: 101, BackupNo: "bk-20260405-001", Type: "manual", Status: "running", SizeBytes: 0, StartedAt: "2026-04-05T02:00:00Z", FinishedAt: ""},
			{ID: 3, InstanceID: 200, BackupNo: "bk-20260404-001", Type: "scheduled", Status: "failed", SizeBytes: 200 * 1024 * 1024, StartedAt: "2026-04-04T03:00:00Z", FinishedAt: "2026-04-04T03:07:00Z"},
		},
		Jobs: []models.Job{
			{ID: 11, JobNo: "job-1001", Type: "createInstance", TargetType: "instance", TargetID: 100, Status: "succeeded", Summary: "实例创建完成", StartedAt: "2026-03-01T02:00:00Z", FinishedAt: "2026-03-01T02:02:00Z"},
			{ID: 12, JobNo: "job-1101", Type: "backup", TargetType: "instance", TargetID: 101, Status: "running", Summary: "备份进行中", StartedAt: "2026-04-05T02:00:00Z", FinishedAt: ""},
			{ID: 13, JobNo: "job-2001", Type: "updateConfig", TargetType: "instance", TargetID: 200, Status: "failed", Summary: "配置校验失败", StartedAt: "2026-04-01T06:00:00Z", FinishedAt: "2026-04-01T06:03:00Z"},
		},
		Alerts: []models.Alert{
			{ID: 21, InstanceID: 100, Severity: "warning", Status: "open", MetricKey: "cpu_usage", Summary: "CPU 使用率 85%", TriggeredAt: "2026-04-05T05:30:00Z"},
			{ID: 22, InstanceID: 101, Severity: "info", Status: "closed", MetricKey: "backup_duration", Summary: "备份延迟 2m", TriggeredAt: "2026-04-04T11:00:00Z"},
			{ID: 23, InstanceID: 200, Severity: "critical", Status: "open", MetricKey: "pod_restarts", Summary: "Pod 重启过多", TriggeredAt: "2026-04-05T02:30:00Z"},
		},
		Audits: []models.AuditEvent{
			{ID: 31, TenantID: 1, Actor: "alice", Action: "updateConfig", Target: "instance", TargetID: 100, Result: "success", CreatedAt: "2026-04-03T08:05:00Z", Metadata: map[string]string{"version": "7"}},
			{ID: 32, TenantID: 1, Actor: "alice", Action: "backup", Target: "instance", TargetID: 101, Result: "running", CreatedAt: "2026-04-05T02:00:00Z", Metadata: map[string]string{"backupNo": "bk-20260405-001"}},
			{ID: 33, TenantID: 2, Actor: "carol", Action: "updateConfig", Target: "instance", TargetID: 200, Result: "failed", CreatedAt: "2026-04-01T06:02:00Z", Metadata: map[string]string{"error": "validation"}},
		},
		Channels: []models.Channel{
			{
				ID:            1,
				Code:          "feishu-main",
				Name:          "飞书总部群",
				Platform:      "feishu",
				Status:        "connected",
				ConnectMethod: "oauth",
				AuthURL:       "https://open.feishu.cn/connect/qrconnect",
				WebhookURL:    "https://hooks.feishu.cn/xxx",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T10:00:00Z",
					Status:      "healthy",
					LatencyMs:   180,
				},
				CallbackSecret: "fs_sig_***91",
				Stats: models.ChannelStats{
					Messages24h:   1840,
					UsersActive24: 320,
					SuccessRate:   0.992,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "飞书工作台", URL: "https://applink.feishu.cn/client/bot"},
					{Label: "会话入口", URL: "https://www.feishu.cn"},
				},
				Notes: "已完成企业应用授权，支持群聊与单聊转接。",
				UpdatedAt: "2026-04-05T10:00:00Z",
				CreatedAt: "2026-03-01T08:00:00Z",
			},
			{
				ID:            2,
				Code:          "wecom-cs",
				Name:          "企业微信客服",
				Platform:      "wecom",
				Status:        "degraded",
				ConnectMethod: "token",
				TokenMasked:   "wx_***8f21",
				WebhookURL:    "https://qyapi.weixin.qq.com/cgi-bin/webhook/send/xxx",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T09:55:00Z",
					Status:      "warning",
					LatencyMs:   520,
				},
				CallbackSecret: "wc_sig_***21",
				Stats: models.ChannelStats{
					Messages24h:   920,
					UsersActive24: 110,
					SuccessRate:   0.941,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "企业微信控制台", URL: "https://work.weixin.qq.com"},
				},
				Notes: "适合作为客服渠道，当前限流需要治理。",
				LastError: "Webhook 返回 429，建议限流或切换备用 key",
				UpdatedAt: "2026-04-05T09:55:00Z",
				CreatedAt: "2026-03-10T10:00:00Z",
			},
			{
				ID:            3,
				Code:          "slack-dev",
				Name:          "Slack DevOps",
				Platform:      "slack",
				Status:        "connecting",
				ConnectMethod: "oauth",
				AuthURL:       "https://slack.com/oauth/v2/authorize",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T09:40:00Z",
					Status:      "warning",
					LatencyMs:   0,
				},
				CallbackSecret: "slack_sig_***84",
				Stats: models.ChannelStats{
					Messages24h:   0,
					UsersActive24: 0,
					SuccessRate:   0,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "Slack App", URL: "https://api.slack.com/apps"},
				},
				Notes: "等待工作区管理员完成 OAuth 安装与事件订阅。",
				LastError: "等待管理员授权完成",
				UpdatedAt: "2026-04-05T09:40:00Z",
				CreatedAt: "2026-04-05T09:30:00Z",
			},
			{
				ID:            4,
				Code:          "telegram-bot",
				Name:          "Telegram Bot",
				Platform:      "telegram",
				Status:        "connected",
				ConnectMethod: "token",
				TokenMasked:   "tg_***2345",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T10:05:00Z",
					Status:      "healthy",
					LatencyMs:   240,
				},
				CallbackSecret: "tg_sig_***45",
				Stats: models.ChannelStats{
					Messages24h:   640,
					UsersActive24: 78,
					SuccessRate:   0.973,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "Telegram Bot", URL: "https://t.me/openclaw_bot"},
				},
				Notes: "当前通过 Bot Token + Webhook 接入。",
				UpdatedAt: "2026-04-05T10:05:00Z",
				CreatedAt: "2026-03-22T12:00:00Z",
			},
			{
				ID:            5,
				Code:          "dingtalk-ops",
				Name:          "钉钉运维群",
				Platform:      "dingtalk",
				Status:        "disconnected",
				ConnectMethod: "oauth",
				AuthURL:       "https://login.dingtalk.com/oauth2/auth",
				CallbackSecret: "dt_sig_***88",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T09:25:00Z",
					Status:      "warning",
					LatencyMs:   0,
				},
				Stats: models.ChannelStats{
					Messages24h:   0,
					UsersActive24: 0,
					SuccessRate:   0,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "钉钉开放平台", URL: "https://open.dingtalk.com"},
				},
				Notes: "支持应用机器人与 Stream/Webhook 两种接收模式。",
				LastError: "尚未完成应用授权",
				UpdatedAt: "2026-04-05T09:25:00Z",
				CreatedAt: "2026-04-02T09:00:00Z",
			},
			{
				ID:            6,
				Code:          "discord-community",
				Name:          "Discord 社群",
				Platform:      "discord",
				Status:        "disconnected",
				ConnectMethod: "token",
				CallbackSecret: "dc_sig_***77",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T08:55:00Z",
					Status:      "critical",
					LatencyMs:   0,
				},
				Stats: models.ChannelStats{
					Messages24h:   0,
					UsersActive24: 0,
					SuccessRate:   0,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "Discord Developer Portal", URL: "https://discord.com/developers/applications"},
				},
				Notes: "需要配置 Interactions Endpoint 与签名校验。",
				LastError: "缺少 Bot Token 与 Interactions Endpoint",
				UpdatedAt: "2026-04-05T08:55:00Z",
				CreatedAt: "2026-04-01T17:00:00Z",
			},
			{
				ID:            7,
				Code:          "whatsapp-support",
				Name:          "WhatsApp 客服",
				Platform:      "whatsapp",
				Status:        "disconnected",
				ConnectMethod: "webhook",
				WebhookURL:    "https://graph.facebook.com/v23.0/phone_number_id/messages",
				CallbackSecret: "wa_sig_***33",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T08:40:00Z",
					Status:      "warning",
					LatencyMs:   0,
				},
				Stats: models.ChannelStats{
					Messages24h:   0,
					UsersActive24: 0,
					SuccessRate:   0,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "Meta Developer", URL: "https://developers.facebook.com/docs/whatsapp"},
				},
				Notes: "建议二期接入 Embedded Signup 与模板消息配置。",
				LastError: "尚未完成 Meta App 绑定",
				UpdatedAt: "2026-04-05T08:40:00Z",
				CreatedAt: "2026-04-01T15:20:00Z",
			},
			{
				ID:            8,
				Code:          "custom-webhook",
				Name:          "自定义 Webhook 渠道",
				Platform:      "custom",
				Status:        "disconnected",
				ConnectMethod: "webhook",
				WebhookURL:    "https://api.openclaw.local/channels/custom-webhook/webhook",
				CallbackSecret: "cw_sig_***66",
				Health: models.ChannelHealth{
					LastChecked: "2026-04-05T08:20:00Z",
					Status:      "warning",
					LatencyMs:   0,
				},
				Stats: models.ChannelStats{
					Messages24h:   0,
					UsersActive24: 0,
					SuccessRate:   0,
				},
				EntryPoints: []models.ChannelEntryPoint{
					{Label: "自定义接入文档", URL: "https://docs.openclaw.local/channels/custom"},
				},
				Notes: "适用于不在平台内置列表中的第三方 IM / CRM / 工单系统。",
				LastError: "等待外部系统回调接入",
				UpdatedAt: "2026-04-05T08:20:00Z",
				CreatedAt: "2026-04-01T12:00:00Z",
			},
		},
		Activities: []models.ChannelActivity{
			{ID: 1, ChannelID: 1, Type: "message_in", Title: "用户：王雷", Summary: "咨询工单状态并触发 FAQ 技能", CreatedAt: "2026-04-05T09:58:00Z"},
			{ID: 2, ChannelID: 2, Type: "webhook", Title: "Webhook 限流", Summary: "429 Too Many Requests", CreatedAt: "2026-04-05T09:55:00Z"},
			{ID: 3, ChannelID: 3, Type: "auth", Title: "等待授权", Summary: "Slack OAuth 未完成", CreatedAt: "2026-04-05T09:40:00Z"},
			{ID: 4, ChannelID: 4, Type: "message_out", Title: "自动回复", Summary: "发送 FAQ 列表", CreatedAt: "2026-04-05T09:35:00Z"},
			{ID: 5, ChannelID: 5, Type: "auth", Title: "待接入", Summary: "钉钉应用未授权", CreatedAt: "2026-04-05T09:25:00Z"},
			{ID: 6, ChannelID: 6, Type: "config", Title: "缺少令牌", Summary: "Discord Bot Token 未配置", CreatedAt: "2026-04-05T08:55:00Z"},
			{ID: 7, ChannelID: 7, Type: "config", Title: "待 Meta 绑定", Summary: "WhatsApp Cloud API 未完成校验", CreatedAt: "2026-04-05T08:40:00Z"},
			{ID: 8, ChannelID: 8, Type: "config", Title: "等待接入", Summary: "自定义 Webhook 尚未收到首条回调", CreatedAt: "2026-04-05T08:20:00Z"},
		},
		Runtimes: []models.InstanceRuntime{
			{InstanceID: 100, PowerState: "running", CPUUsagePercent: 58, MemoryUsagePercent: 63, DiskUsagePercent: 48, APIRequests24h: 28400, APITokens24h: 1254000, LastSeenAt: "2026-04-05T10:20:00Z"},
			{InstanceID: 101, PowerState: "running", CPUUsagePercent: 34, MemoryUsagePercent: 41, DiskUsagePercent: 37, APIRequests24h: 8600, APITokens24h: 342000, LastSeenAt: "2026-04-05T10:18:00Z"},
			{InstanceID: 200, PowerState: "running", CPUUsagePercent: 72, MemoryUsagePercent: 57, DiskUsagePercent: 53, APIRequests24h: 19200, APITokens24h: 980000, LastSeenAt: "2026-04-05T10:16:00Z"},
		},
		Credentials: []models.InstanceCredential{
			{InstanceID: 100, AdminUser: "admin", PasswordMasked: "Adm!***92", LastRotatedAt: "2026-04-01T09:00:00Z", RequiresReset: false},
			{InstanceID: 101, AdminUser: "admin", PasswordMasked: "Stg!***15", LastRotatedAt: "2026-03-28T13:20:00Z", RequiresReset: true},
			{InstanceID: 200, AdminUser: "ops", PasswordMasked: "Nv!***37", LastRotatedAt: "2026-03-30T07:40:00Z", RequiresReset: false},
		},
		PlanOffers: []models.PlanOffer{
			{ID: 1, Code: "trial", Name: "Trial", MonthlyPrice: 0, CPU: "1", Memory: "2Gi", Storage: "10Gi", Highlight: "快速验证", Features: []string{"单实例", "手动备份", "社区支持"}},
			{ID: 2, Code: "standard", Name: "Standard", MonthlyPrice: 299, CPU: "2", Memory: "4Gi", Storage: "30Gi", Highlight: "中小团队", Features: []string{"双副本", "定时备份", "基础告警"}},
			{ID: 3, Code: "pro", Name: "Pro", MonthlyPrice: 899, CPU: "4", Memory: "8Gi", Storage: "80Gi", Highlight: "生产推荐", Features: []string{"多渠道接入", "审计", "管理员视图"}},
		},
		Orders: []models.Order{
			{ID: 1, TenantID: 1, InstanceID: 100, PlanCode: "pro", Action: "buy", Status: "active", Amount: 899, CreatedAt: "2026-03-01T08:00:00Z"},
			{ID: 2, TenantID: 1, InstanceID: 101, PlanCode: "standard", Action: "renew", Status: "pending", Amount: 299, CreatedAt: "2026-04-05T09:45:00Z"},
		},
		Tickets: []models.Ticket{
			{ID: 1, TicketNo: "TK-20260405-001", TenantID: 1, InstanceID: 101, Title: "备份失败需要排查", Category: "backup", Severity: "high", Status: "in_progress", Reporter: "陆明舟", Assignee: "ops-admin", Description: "凌晨备份任务异常，需要确认对象存储写入状态。", CreatedAt: "2026-04-05T08:20:00Z", UpdatedAt: "2026-04-05T09:10:00Z"},
			{ID: 2, TicketNo: "TK-20260405-002", TenantID: 2, InstanceID: 200, Title: "实例 CPU 偏高", Category: "performance", Severity: "medium", Status: "open", Reporter: "Carol", Assignee: "", Description: "请求高峰期间 CPU 使用率持续高于 70%。", CreatedAt: "2026-04-05T09:30:00Z", UpdatedAt: "2026-04-05T09:30:00Z"},
		},
		Brands: []models.OEMBrand{
			{ID: 1, Code: "openclaw", Name: "OpenClaw", Status: "active", LogoURL: "https://assets.openclaw.local/logo.svg", FaviconURL: "https://assets.openclaw.local/favicon.svg", SupportEmail: "support@openclaw.local", SupportURL: "https://support.openclaw.local", Domains: []string{"console.openclaw.local", "portal.openclaw.local"}, UpdatedAt: "2026-04-05T09:00:00Z", CreatedAt: "2026-03-01T08:00:00Z"},
			{ID: 2, Code: "acme-oem", Name: "Acme AI Workspace", Status: "active", LogoURL: "https://assets.acme.local/logo.svg", FaviconURL: "https://assets.acme.local/favicon.svg", SupportEmail: "it@acme.example.com", SupportURL: "https://acme.example.com/help", Domains: []string{"ai.acme.example.com"}, UpdatedAt: "2026-04-05T09:20:00Z", CreatedAt: "2026-03-15T10:00:00Z"},
		},
		BrandThemes: []models.OEMTheme{
			{BrandID: 1, PrimaryColor: "#1d6bff", SecondaryColor: "#5c7bff", AccentColor: "#22c55e", SurfaceMode: "hybrid", FontFamily: "MiSans VF", Radius: "20px"},
			{BrandID: 2, PrimaryColor: "#0f766e", SecondaryColor: "#14b8a6", AccentColor: "#f59e0b", SurfaceMode: "light", FontFamily: "MiSans VF", Radius: "16px"},
		},
		BrandFeatures: []models.OEMFeatureFlags{
			{BrandID: 1, PortalEnabled: true, AdminEnabled: true, ChannelsEnabled: true, TicketsEnabled: true, PurchaseEnabled: true, RuntimeControlEnabled: true, AuditEnabled: true, SSOEnabled: true},
			{BrandID: 2, PortalEnabled: true, AdminEnabled: false, ChannelsEnabled: true, TicketsEnabled: true, PurchaseEnabled: false, RuntimeControlEnabled: false, AuditEnabled: false, SSOEnabled: true},
		},
		BrandBindings: []models.TenantBrandBinding{
			{TenantID: 1, BrandID: 2, BindingMode: "dedicated", UpdatedAt: "2026-04-05T09:20:00Z"},
			{TenantID: 2, BrandID: 1, BindingMode: "shared", UpdatedAt: "2026-04-05T09:00:00Z"},
		},
	}
}
